baseURL = "https://oli3012.github.io/"
languageCode = "en-us"
title = "oli3012 blog"
theme = "m10c"

[params]
  author = "Olivier Therrien"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/oli3012"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/volfaze"